name: Docker Build and Deploy
on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  SERVICE_NAME: carbot-scraper
 
permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Assume AWS role
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: ${{ env.AWS_REGION }}
    - name: Copy app config file from s3
      working-directory: WebScraper
      run: |
        aws s3 cp s3://carbot-app-config-files/webscraper/appsettings.json ./

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      working-directory: WebScraper
      run: |
        docker build -t $REGISTRY/$SERVICE_NAME:$IMAGE_TAG .
        docker push $REGISTRY/$SERVICE_NAME:$IMAGE_TAG
